{% set version = "1.1.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ctxr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ctxR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ctxR/ctxR_{{ version }}.tar.gz
  sha256: a564333c97261ffcf31baf8f343ddab00d729d6dc1ebce2321a46a7d338aea9a

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-data.table
    - r-httr
    - r-jsonlite
    - r-lifecycle
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-urltools
  run:
    - r-base
    - r-cli
    - r-data.table
    - r-httr
    - r-jsonlite
    - r-lifecycle
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-urltools

test:
  commands:
    - $R -e "library('ctxR')"           # [not win]
    - "\"%R%\" -e \"library('ctxR')\""  # [win]

about:
  home: https://github.com/USEPA/ctxR
  license: GPL-3.0-or-later
  summary: Access chemical, hazard, bioactivity, and exposure data from the Computational Toxicology and Exposure ('CTX') APIs <https://api-ccte.epa.gov/docs/>. 'ctxR' was developed to streamline the process of accessing the information available through the 'CTX' APIs without requiring prior knowledge of how to use APIs.
    Most data is also available on the CompTox Chemical Dashboard ('CCD') <https://comptox.epa.gov/dashboard/> and other resources found at the EPA Computational Toxicology and Exposure Online Resources <https://www.epa.gov/comptox-tools>.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
